Report missing tools in scripts/strip.py
It is possible that tools scripts/strip.py needs does not exist in
host environment at all. In this case error message should be more
telling.

Before:
  ...long stack trace...
  OSError: [Errno 2] No such file or directory
Now:
  Error: Couldn't execute command 'objcopy --only-keep-debug target/executable/test -o ./install/bin/test.dbg': No such file or directory

Change-Id: I8ffc13d55808499e4a5bf811b7ba3e42ed54714d
Signed-off-by: Ali Utku Selen <ali.utku.selen@arm.com>